import { z } from "zod"
import { Log } from "../util/log"
import { callLLM } from "./llm-wrapper"

const log = Log.create({ service: "multi-thread-narrative" })

/**
 * LLM Client interface for semantic conflict detection and intelligent arbitration.
 * Allows dependency injection of any LLM provider while keeping the class testable.
 */
export interface LLMClient {
  call(prompt: string, options?: { callType?: string }): Promise<string>
}

/**
 * Default LLM client wrapping the novel engine's callLLM function.
 */
class DefaultLLMClient implements LLMClient {
  async call(prompt: string, options?: { callType?: string }): Promise<string> {
    const result = await callLLM({
      prompt,
      callType: options?.callType || "narrative_conflict",
      temperature: 0.2,
    })
    return result.text.trim()
  }
}

/**
 * Reconciliation plan generated by LLM arbitration.
 */
export interface ReconciliationPlan {
  /** How to resolve: "modify_thread_a" | "modify_thread_b" | "merge_events" | "add_bridge" */
  action: "modify_thread_a" | "modify_thread_b" | "merge_events" | "add_bridge"
  /** The reconciled narrative text that both threads should adopt */
  reconciledSummary: string
  /** Suggested events after reconciliation */
  reconciledEvents: string[]
  /** LLM's reasoning for this resolution */
  reasoning: string
  /** Which thread's version is closer to the truth (by thread name) */
  authoritativeThread: string
}

/**
 * Conflict detection result with LLM-assessed contradiction type.
 */
export interface SemanticConflict {
  type: "contradiction" | "timing" | "character" | "location" | "causal"
  description: string
  severity: "low" | "medium" | "high"
  /** LLM-confirmed: whether this is truly a narrative contradiction */
  llmConfirmed: boolean
  /** Threads involved */
  threadA: string
  threadB: string
  /** Specific conflicting content */
  conflictA: string
  conflictB: string
  resolution?: string
  reconciliationPlan?: ReconciliationPlan
}

/**
 * Circuit breaker states for LLM calls.
 * CLOSED: normal operation, all calls go through
 * OPEN: failures exceeded threshold, all calls bypass to fallback
 * HALF_OPEN: recovery window expired, next call is a probe
 */
type CircuitState = "closed" | "open" | "half_open"

/**
 * Result of a circuit-guarded LLM call.
 */
interface CircuitGuardResult<T> {
  /** Whether the call was allowed through the circuit */
  allowed: boolean
  /** The result if allowed, or undefined if blocked */
  result?: T
  /** Reason for blocking (if blocked) */
  reason?: "circuit_open" | "no_client"
}

/**
 * Multi-Thread Narrative Executor
 *
 * Enhanced integration with orchestrator:
 * - Supports progress callbacks for real-time status updates
 * - Integrates with observability for performance tracking
 * - Provides structured execution context for better debugging
 *
 * Usage with orchestrator:
 * ```typescript
 * const executor = new MultiThreadNarrativeExecutor()
 * executor.setProgressCallback((progress) => {
 *   observability.recordThreadProgress(progress)
 * })
 * ```
 */

export const NarrativeThreadSchema = z.object({
  id: z.string(),
  name: z.string(),
  povCharacter: z.string(),
  currentChapter: z.number(),
  lastSyncChapter: z.number(),
  status: z.enum(["active", "paused", "completed", "merged"]),
  priority: z.number().min(1).max(10),
  chapters: z.array(
    z.object({
      number: z.number(),
      summary: z.string(),
      events: z.array(z.string()),
      characters: z.array(z.string()),
      location: z.string().optional(),
    }),
  ),
  pendingEvents: z.array(z.string()),
  convergesWith: z.array(z.string()).optional(),
})

export type NarrativeThread = z.infer<typeof NarrativeThreadSchema>

export interface ThreadSynchronization {
  threadId: string
  lastSyncChapter: number
  pendingConflicts: Array<{
    type: "contradiction" | "timing" | "character" | "location"
    description: string
    severity: "low" | "medium" | "high"
    resolution?: string
  }>
}

export interface MultiThreadConfig {
  maxActiveThreads: number
  syncInterval: number // chapters between syncs
  enableConflictDetection: boolean
  autoResolveConflicts: boolean
  /** Enable LLM-based semantic conflict detection (Upgrade 1) */
  enableLLMConflictDetection: boolean
  /** Enable LLM-based intelligent arbitration (Upgrade 2) */
  enableLLMArbitration: boolean
}

const DEFAULT_CONFIG: MultiThreadConfig = {
  maxActiveThreads: 5,
  syncInterval: 3,
  enableConflictDetection: true,
  autoResolveConflicts: false,
  enableLLMConflictDetection: true,
  enableLLMArbitration: true,
}

export class MultiThreadNarrativeExecutor {
  private threads: Map<string, NarrativeThread> = new Map()
  private config: MultiThreadConfig
  private globalChapter: number = 1
  private synchronizationBarriers: Map<number, Set<string>> = new Map()
  /** Upgrade 3: LLM client for semantic conflict detection and arbitration */
  private llmClient: LLMClient

  // ── Dimension 1: Circuit Breaker for LLM calls ──────────────────────────
  /** Tracks consecutive LLM failures across all call sites */
  private llmFailureCount = 0
  /** Current circuit state. When "open", all LLM calls bypass to fallback */
  private circuitState: CircuitState = "closed"
  /** Timestamp (ms) when the circuit was opened. Used to calculate recovery window */
  private circuitOpenedAt: number | null = null
  /** Circuit breaker thresholds */
  private readonly CIRCUIT_FAILURE_THRESHOLD = 3 // consecutive failures to open
  private readonly CIRCUIT_RECOVERY_MS = 5 * 60 * 1000 // 5 minutes

  // ── Dimension 2: Semantic Deduplication Cache ──────────────────────────
  /**
   * Maps a normalized hash of (eventA, eventB) → LLM contradiction verdict.
   * Prevents calling LLM for semantically identical event pairs.
   * Uses simple word-bag hashing: sort unique lowercase alphabetic tokens.
   * TTL: entries are retained for the lifetime of the executor instance.
   */
  private semanticConflictCache = new Map<string, boolean>()
  /** Arbitration cache: maps conflict signature → ReconciliationPlan */
  private arbitrationCache = new Map<string, ReconciliationPlan>()
  /** Max cache size to prevent unbounded memory growth */
  private readonly MAX_CACHE_SIZE = 500

  constructor(config: Partial<MultiThreadConfig> = {}, llmClient?: LLMClient) {
    this.config = { ...DEFAULT_CONFIG, ...config }
    // Upgrade 3: Dependency injection with fallback to default client
    this.llmClient = llmClient || new DefaultLLMClient()
  }

  // ─────────────────────────────────────────────────────────────────────
  // Dimension 1: Circuit Breaker Implementation
  // ─────────────────────────────────────────────────────────────────────

  /**
   * Circuit breaker guard for LLM calls.
   *
   * State machine:
   *   CLOSED → OPEN       : consecutive failures >= threshold
   *   OPEN → HALF_OPEN    : recovery timer expired
   *   HALF_OPEN → CLOSED  : probe call succeeded (reset counter)
   *   HALF_OPEN → OPEN    : probe call failed (reset timer)
   *
   * Returns { allowed: true } if the call should proceed, or
   * { allowed: false, reason: "circuit_open" } if it should be bypassed.
   */
  private guardLLMCall(): CircuitGuardResult<void> {
    if (!this.llmClient) {
      return { allowed: false, reason: "no_client" }
    }

    switch (this.circuitState) {
      case "closed":
        // Normal operation — allow through
        return { allowed: true }

      case "open": {
        // Check if recovery window has expired
        const elapsed = Date.now() - (this.circuitOpenedAt ?? 0)
        if (elapsed >= this.CIRCUIT_RECOVERY_MS) {
          // Transition to HALF_OPEN: allow one probe call
          this.circuitState = "half_open"
          log.info("circuit_half_open", {
            openDuration: `${Math.round(elapsed / 1000)}s`,
          })
          return { allowed: true }
        }
        // Still in recovery window — block
        return { allowed: false, reason: "circuit_open" }
      }

      case "half_open":
        // Already in probe mode — only one call should be in flight.
        // If another call arrives, block it to avoid hammering the LLM.
        return { allowed: false, reason: "circuit_open" }

      default:
        return { allowed: true }
    }
  }

  /** Record a successful LLM call — reset circuit breaker to CLOSED */
  private recordLLMSuccess(): void {
    if (this.circuitState === "half_open") {
      // Probe succeeded — circuit fully recovers
      log.info("circuit_recovered", {
        previousFailures: this.llmFailureCount,
      })
    }
    this.llmFailureCount = 0
    this.circuitState = "closed"
    this.circuitOpenedAt = null
  }

  /** Record a failed LLM call — may trigger circuit OPEN */
  private recordLLMFailure(): void {
    this.llmFailureCount++

    if (this.circuitState === "half_open") {
      // Probe failed — re-open circuit with fresh timer
      this.circuitState = "open"
      this.circuitOpenedAt = Date.now()
      log.warn("circuit_reopened", { failureCount: this.llmFailureCount })
      return
    }

    if (this.llmFailureCount >= this.CIRCUIT_FAILURE_THRESHOLD) {
      this.circuitState = "open"
      this.circuitOpenedAt = Date.now()
      log.warn("circuit_opened", {
        failureCount: this.llmFailureCount,
        recoveryIn: `${this.CIRCUIT_RECOVERY_MS / 1000}s`,
      })
    }
  }

  /** Get current circuit breaker status (for debugging/observability) */
  getCircuitBreakerStatus(): {
    state: CircuitState
    failureCount: number
    openedAt: number | null
    recoveryWindowRemaining: number | null
  } {
    let recoveryWindowRemaining: number | null = null
    if (this.circuitState === "open" && this.circuitOpenedAt !== null) {
      const elapsed = Date.now() - this.circuitOpenedAt
      recoveryWindowRemaining = Math.max(0, this.CIRCUIT_RECOVERY_MS - elapsed)
    }
    return {
      state: this.circuitState,
      failureCount: this.llmFailureCount,
      openedAt: this.circuitOpenedAt,
      recoveryWindowRemaining,
    }
  }

  /** Manually reset the circuit breaker (useful for testing or manual recovery) */
  resetCircuitBreaker(): void {
    this.llmFailureCount = 0
    this.circuitState = "closed"
    this.circuitOpenedAt = null
    log.info("circuit_manually_reset")
  }

  // ─────────────────────────────────────────────────────────────────────
  // Dimension 2: Semantic Deduplication Cache Helpers
  // ─────────────────────────────────────────────────────────────────────

  /**
   * Generate a normalized hash key for a pair of event strings.
   *
   * Algorithm:
   * 1. Concatenate both events
   * 2. Lowercase + remove punctuation (keep alphanumeric + spaces)
   * 3. Split into words, remove stopwords ("the", "a", "is", etc.)
   * 4. Sort alphabetically → join with "|"
   * 5. Hash with simple FNV-1a
   *
   * This ensures "The guard died" and "died, the guard!" produce the same key,
   * while "guard helped" produces a different one.
   */
  private buildEventConflictKey(eventA: string, eventB: string): string {
    const stopwords = new Set([
      "the", "a", "an", "is", "was", "were", "be", "been", "being",
      "have", "has", "had", "do", "does", "did", "will", "would",
      "could", "should", "may", "might", "shall", "can",
      "and", "or", "but", "if", "then", "than", "so", "as",
      "of", "to", "in", "for", "on", "with", "at", "by", "from",
      "not", "no", "that", "this", "these", "those", "it", "its",
    ])

    const combined = `${eventA} ${eventB}`
      .toLowerCase()
      .replace(/[^a-z0-9\s]/g, "") // Remove punctuation
      .split(/\s+/)
      .filter((w) => w.length > 1 && !stopwords.has(w))
      .sort()
      .join("|")

    // FNV-1a hash (32-bit)
    let hash = 0x811c9dc5
    for (let i = 0; i < combined.length; i++) {
      hash ^= combined.charCodeAt(i)
      hash = Math.imul(hash, 0x01000193)
    }
    return (hash >>> 0).toString(36) // Unsigned hex → base36
  }

  /**
   * Build a cache key for arbitration based on the conflict's normalized signature.
   */
  private buildArbitrationKey(
    threadAName: string,
    threadBName: string,
    summaryA: string,
    summaryB: string,
    conflictType: string,
  ): string {
    const normalizedA = summaryA.toLowerCase().replace(/[^a-z0-9\s]/g, "").slice(0, 200)
    const normalizedB = summaryB.toLowerCase().replace(/[^a-z0-9\s]/g, "").slice(0, 200)
    const combined = `${threadAName}|${threadBName}|${conflictType}|${normalizedA}|${normalizedB}`

    let hash = 0x811c9dc5
    for (let i = 0; i < combined.length; i++) {
      hash ^= combined.charCodeAt(i)
      hash = Math.imul(hash, 0x01000193)
    }
    return `arb_${(hash >>> 0).toString(36)}`
  }

  /** Safely set a value in the semantic conflict cache with eviction */
  private setSemanticCache(key: string, value: boolean): void {
    if (this.semanticConflictCache.size >= this.MAX_CACHE_SIZE) {
      // Evict oldest entry (FIFO — Map preserves insertion order)
      const firstKey = this.semanticConflictCache.keys().next().value
      if (firstKey !== undefined) {
        this.semanticConflictCache.delete(firstKey)
      }
    }
    this.semanticConflictCache.set(key, value)
  }

  /** Safely set a value in the arbitration cache with eviction */
  private setArbitrationCache(key: string, value: ReconciliationPlan): void {
    if (this.arbitrationCache.size >= this.MAX_CACHE_SIZE) {
      const firstKey = this.arbitrationCache.keys().next().value
      if (firstKey !== undefined) {
        this.arbitrationCache.delete(firstKey)
      }
    }
    this.arbitrationCache.set(key, value)
  }

  // ─────────────────────────────────────────────────────────────────────
  // Public Methods
  // ─────────────────────────────────────────────────────────────────────

  createThread(name: string, povCharacter: string, priority: number = 5): NarrativeThread {
    const id = `thread_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`

    const thread: NarrativeThread = {
      id,
      name,
      povCharacter,
      currentChapter: this.globalChapter,
      lastSyncChapter: this.globalChapter,
      status: "active",
      priority,
      chapters: [],
      pendingEvents: [],
      convergesWith: [],
    }

    this.threads.set(id, thread)
    log.info("thread_created", { id, name, povCharacter, priority })

    return thread
  }

  async advanceThread(
    threadId: string,
    chapterData: {
      summary: string
      events: string[]
      characters: string[]
      location?: string
    },
  ): Promise<NarrativeThread> {
    const thread = this.threads.get(threadId)
    if (!thread) {
      throw new Error(`Thread ${threadId} not found`)
    }

    if (thread.status !== "active") {
      throw new Error(`Thread ${threadId} is ${thread.status}, cannot advance`)
    }

    const nextChapter = thread.currentChapter + 1
    thread.currentChapter = nextChapter

    thread.chapters.push({
      number: nextChapter,
      summary: chapterData.summary,
      events: chapterData.events,
      characters: chapterData.characters,
      location: chapterData.location,
    })

    // Check if we need to synchronize
    if (this.needsSynchronization(thread)) {
      await this.synchronizeThread(thread)
    }

    this.threads.set(threadId, thread)
    log.info("thread_advanced", { threadId, chapter: nextChapter })

    return thread
  }

  private needsSynchronization(thread: NarrativeThread): boolean {
    return thread.currentChapter - thread.lastSyncChapter >= this.config.syncInterval
  }

  private async synchronizeThread(thread: NarrativeThread): Promise<void> {
    log.info("synchronizing_thread", { threadId: thread.id })

    // Find other active threads at similar chapter
    const threadsToSync = Array.from(this.threads.values()).filter(
      (t) => t.id !== thread.id && t.status === "active" && Math.abs(t.currentChapter - thread.currentChapter) <= 2,
    )

    if (threadsToSync.length === 0) {
      thread.lastSyncChapter = thread.currentChapter
      return
    }

    // Detect conflicts
    if (this.config.enableConflictDetection) {
      const conflicts = await this.detectConflicts(thread, threadsToSync)

      if (conflicts.length > 0) {
        log.warn("conflicts_detected", { count: conflicts.length, threadId: thread.id })

        if (this.config.autoResolveConflicts) {
          await this.resolveConflicts(thread, conflicts)
        }
      }
    }

    thread.lastSyncChapter = thread.currentChapter
    this.threads.set(thread.id, thread)
  }

  /**
   * Detect narrative conflicts between threads using semantic analysis.
   *
   * UPGRADE 1 — Semantic Conflict Detection:
   * Replaces naive `.includes("not")` string matching with LLM-based semantic comparison.
   * Can detect contradictions like "protagonist dies" vs "protagonist runs away" even
   * when the text shares no common keywords.
   *
   * Fallback: if LLM is disabled or fails, falls back to rule-based heuristics
   * (location conflicts, explicit negation patterns).
   */
  private async detectConflicts(
    thread: NarrativeThread,
    otherThreads: NarrativeThread[],
  ): Promise<SemanticConflict[]> {
    const conflicts: SemanticConflict[] = []

    for (const other of otherThreads) {
      const threadChapter = thread.chapters[thread.chapters.length - 1]
      const otherChapter = other.chapters[other.chapters.length - 1]
      if (!threadChapter || !otherChapter) continue

      // ── Rule-based pre-check: same character in different locations (always a conflict)
      const commonChars = threadChapter.characters.filter((c) =>
        otherChapter.characters.includes(c),
      )
      if (commonChars.length > 0) {
        const threadLoc = threadChapter.location
        const otherLoc = otherChapter.location
        if (threadLoc && otherLoc && threadLoc !== otherLoc) {
          conflicts.push({
            type: "character",
            description: `Character(s) ${commonChars.join(", ")} appear in both ${thread.name} (${threadLoc}) and ${other.name} (${otherLoc}) simultaneously`,
            severity: "high",
            llmConfirmed: true, // This is always a real conflict
            threadA: thread.name,
            threadB: other.name,
            conflictA: `${commonChars.join(", ")} at ${threadLoc}`,
            conflictB: `${commonChars.join(", ")} at ${otherLoc}`,
          })
        }
      }

      // ── UPGRADE 1: LLM-based semantic conflict detection
      if (this.config.enableLLMConflictDetection) {
        const threadEvents = threadChapter.events
        const otherEvents = otherChapter.events

        if (threadEvents.length > 0 && otherEvents.length > 0) {
          const semanticConflicts = await this.detectSemanticConflicts(
            thread.name,
            threadChapter.summary,
            threadEvents,
            other.name,
            otherChapter.summary,
            otherEvents,
          )
          conflicts.push(...semanticConflicts)
        }

        // Also check summaries for semantic contradictions (not just events)
        const summaryConflict = await this.detectSummaryContradiction(
          thread.name,
          threadChapter.summary,
          other.name,
          otherChapter.summary,
        )
        if (summaryConflict) {
          conflicts.push(summaryConflict)
        }
      } else {
        // Fallback: old rule-based detection (negation patterns)
        const threadEvents = new Set(threadChapter.events)
        const otherEvents = new Set(otherChapter.events)
        for (const event of threadEvents) {
          if (
            [...otherEvents].some(
              (e) => e.includes(`not ${event}`) || e.includes(`failed ${event}`) || e.includes(`failed to ${event}`),
            )
          ) {
            conflicts.push({
              type: "contradiction",
              description: `Contradictory events: "${event}" in ${thread.name} vs negation in ${other.name}`,
              severity: "high",
              llmConfirmed: true,
              threadA: thread.name,
              threadB: other.name,
              conflictA: event,
              conflictB: `negation of "${event}"`,
            })
          }
        }
      }
    }

    log.info("conflict_detection_complete", {
      total: conflicts.length,
      llmConfirmed: conflicts.filter((c) => c.llmConfirmed).length,
      highSeverity: conflicts.filter((c) => c.severity === "high").length,
    })

    return conflicts
  }

  /**
   * Compare events from two threads using LLM to detect semantic contradictions.
   * Handles cases like "protagonist killed the guard" vs "protagonist was captured by the guard"
   * which have no string overlap but are logically incompatible.
   *
   * UPGRADE — Dimension 1 (Circuit Breaker): checks guard before each LLM call.
   * UPGRADE — Dimension 2 (Semantic Cache): checks dedup cache before each LLM call.
   */
  private async detectSemanticConflicts(
    threadAName: string,
    summaryA: string,
    eventsA: string[],
    threadBName: string,
    summaryB: string,
    eventsB: string[],
  ): Promise<SemanticConflict[]> {
    const conflicts: SemanticConflict[] = []

    // Compare each event from thread A against all events from thread B
    for (const eventA of eventsA) {
      for (const eventB of eventsB) {
        // Skip if events are identical or trivially compatible
        if (eventA === eventB) continue

        // ── Dimension 2: Check semantic deduplication cache
        const cacheKey = this.buildEventConflictKey(eventA, eventB)
        const cachedResult = this.semanticConflictCache.get(cacheKey)
        if (cachedResult !== undefined) {
          // Cache HIT — skip LLM entirely, use stored verdict
          if (cachedResult) {
            conflicts.push({
              type: "contradiction",
              description: `Semantic contradiction: "${eventA}" (${threadAName}) vs "${eventB}" (${threadBName}) [cached]`,
              severity: "high",
              llmConfirmed: true,
              threadA: threadAName,
              threadB: threadBName,
              conflictA: eventA,
              conflictB: eventB,
            })
            log.info("semantic_conflict_cache_hit", { eventA: eventA.slice(0, 40), eventB: eventB.slice(0, 40) })
          }
          continue
        }

        // ── Dimension 1: Check circuit breaker before LLM call
        const guard = this.guardLLMCall()
        if (!guard.allowed) {
          // Circuit is OPEN — bypass to fallback logic below
          log.debug("llm_call_blocked_circuit_open", { eventA: eventA.slice(0, 40) })
          continue
        }

        try {
          const prompt = `You are a narrative consistency checker. Determine if the following two events from parallel story threads are logically contradictory.

Thread "${threadAName}" event: ${eventA}
Context: ${summaryA.slice(0, 200)}

Thread "${threadBName}" event: ${eventB}
Context: ${summaryB.slice(0, 200)}

Question: Are these two events logically incompatible? That is, if event A happened, could event B also have happened in the same timeline?
Answer ONLY with "YES" (they contradict) or "NO" (they can coexist).`

          const response = await this.llmClient.call(prompt, {
            callType: "thread_event_conflict",
          })

          const isContradiction = response.trim().toUpperCase().startsWith("YES")

          // Cache HIT: store the result for future deduplication
          this.setSemanticCache(cacheKey, isContradiction)

          if (isContradiction) {
            conflicts.push({
              type: "contradiction",
              description: `Semantic contradiction: "${eventA}" (${threadAName}) vs "${eventB}" (${threadBName})`,
              severity: "high",
              llmConfirmed: true,
              threadA: threadAName,
              threadB: threadBName,
              conflictA: eventA,
              conflictB: eventB,
            })
            log.info("semantic_conflict_detected", {
              eventA,
              eventB,
              threadA: threadAName,
              threadB: threadBName,
            })
          }

          // ── Dimension 1: Record success for circuit breaker
          this.recordLLMSuccess()
        } catch (e) {
          // ── Dimension 1: Record failure for circuit breaker
          this.recordLLMFailure()

          log.warn("llm_conflict_check_failed", {
            eventA: eventA.slice(0, 50),
            eventB: eventB.slice(0, 50),
            error: String(e),
            circuitState: this.circuitState,
            failureCount: this.llmFailureCount,
          })
          // Fail-safe: don't block on LLM errors, just skip this pair
        }
      }
    }

    return conflicts
  }

  /**
   * Check if two chapter summaries describe mutually incompatible narrative states.
   * E.g., "The city was destroyed" vs "The city flourished in peace" — different events,
   * same subject, incompatible outcomes.
   *
   * UPGRADE — Dimension 1 (Circuit Breaker): checks guard before LLM call.
   * UPGRADE — Dimension 2 (Semantic Cache): deduplicates by normalized summary content.
   */
  private async detectSummaryContradiction(
    threadAName: string,
    summaryA: string,
    threadBName: string,
    summaryB: string,
  ): Promise<SemanticConflict | null> {
    if (!summaryA || !summaryB) return null

    // ── Dimension 2: Check semantic cache
    const cacheKey = this.buildEventConflictKey(summaryA.slice(0, 200), summaryB.slice(0, 200))
    const cachedResult = this.semanticConflictCache.get(cacheKey)
    if (cachedResult !== undefined) {
      if (cachedResult) {
        log.info("summary_conflict_cache_hit", { threadA: threadAName, threadB: threadBName })
        return {
          type: "causal",
          description: `Narrative incompatibility between ${threadAName} and ${threadBName} [cached]`,
          severity: "medium",
          llmConfirmed: true,
          threadA: threadAName,
          threadB: threadBName,
          conflictA: summaryA.slice(0, 200),
          conflictB: summaryB.slice(0, 200),
        }
      }
      return null
    }

    // ── Dimension 1: Check circuit breaker
    const guard = this.guardLLMCall()
    if (!guard.allowed) {
      log.debug("summary_llm_call_blocked_circuit_open", { threadA: threadAName })
      return null
    }

    try {
      const prompt = `You are a narrative consistency checker. Determine if the following chapter summaries from parallel story threads describe mutually incompatible storylines.

Thread "${threadAName}" summary:
${summaryA}

Thread "${threadBName}" summary:
${summaryB}

These threads are supposed to be part of the same overall narrative. Are the described outcomes, character fates, or world states fundamentally incompatible?
Answer ONLY with "YES" (incompatible) or "NO" (compatible).`

      const response = await this.llmClient.call(prompt, {
        callType: "thread_summary_conflict",
      })

      const isIncompatible = response.trim().toUpperCase().startsWith("YES")

      // Cache the result
      this.setSemanticCache(cacheKey, isIncompatible)

      if (isIncompatible) {
        // ── Dimension 1: Record success
        this.recordLLMSuccess()
        return {
          type: "causal",
          description: `Narrative incompatibility between ${threadAName} and ${threadBName}: the described storylines lead to fundamentally different outcomes`,
          severity: "medium",
          llmConfirmed: true,
          threadA: threadAName,
          threadB: threadBName,
          conflictA: summaryA.slice(0, 200),
          conflictB: summaryB.slice(0, 200),
        }
      }

      this.recordLLMSuccess()
    } catch (e) {
      this.recordLLMFailure()
      log.warn("llm_summary_check_failed", {
        threadA: threadAName,
        threadB: threadBName,
        error: String(e),
        circuitState: this.circuitState,
        failureCount: this.llmFailureCount,
      })
    }

    return null
  }

  /**
   * Resolve conflicts using LLM-driven intelligent arbitration.
   *
   * UPGRADE 2 — Intelligent Arbitration:
   * Instead of blindly overwriting with higher-priority thread, calls LLM to generate
   * a reconciliation plan. Options include:
   *   - modify_thread_a: Adjust thread A's events to fit thread B's worldview
   *   - modify_thread_b: Adjust thread B's events to fit thread A's worldview
   *   - merge_events: Fuse both events into a new coherent narrative
   *   - add_bridge: Insert a transitional event that explains the difference
   *
   * Fallback: if LLM is disabled or circuit breaker is open, `arbitrateConflict`
   * automatically returns a priority-based plan via `buildFallbackPlan`.
   */
  private async resolveConflicts(
    thread: NarrativeThread,
    conflicts: SemanticConflict[],
  ): Promise<void> {
    for (const conflict of conflicts) {
      // Find the other thread involved
      const otherThreadName =
        conflict.threadA === thread.name ? conflict.threadB : conflict.threadA
      const otherThread = Array.from(this.threads.values()).find(
        (t) => t.name === otherThreadName,
      )
      if (!otherThread) {
        // Fallback: can't find other thread
        conflict.resolution = `Other thread not found. Keeping ${thread.name}'s version.`
        continue
      }

      // ── UPGRADE 2: LLM-based intelligent arbitration
      // Circuit breaker and cache are handled inside arbitrateConflict
      if (!this.config.enableLLMArbitration) {
        // User explicitly disabled LLM arbitration — use priority-based plan
        const fallbackPlan = this.buildFallbackPlan(thread, otherThread)
        conflict.reconciliationPlan = fallbackPlan
        conflict.resolution = `[Priority Fallback] ${fallbackPlan.action}: ${fallbackPlan.reasoning}`
        continue
      }

      try {
        const reconciliationPlan = await this.arbitrateConflict(
          thread,
          otherThread,
          conflict,
        )
        conflict.reconciliationPlan = reconciliationPlan
        conflict.resolution = `[LLM Arbitration] ${reconciliationPlan.action}: ${reconciliationPlan.reasoning}`

        log.info("conflict_arbitrated", {
          conflictType: conflict.type,
          action: reconciliationPlan.action,
          authoritativeThread: reconciliationPlan.authoritativeThread,
        })
      } catch (e) {
        log.warn("llm_arbitration_unexpected_error", {
          conflictType: conflict.type,
          error: String(e),
        })
        // Ultimate fallback: priority-based resolution
        const fallbackPlan = this.buildFallbackPlan(thread, otherThread)
        conflict.resolution = `[Fallback] ${fallbackPlan.action}: ${fallbackPlan.reasoning}`
      }
    }

    log.info("conflicts_resolved", {
      count: conflicts.length,
      llmArbitrated: conflicts.filter((c) => c.reconciliationPlan).length,
      threadId: thread.id,
    })
  }

  /**
   * Call LLM to generate a reconciliation plan for a specific conflict.
   * Returns a structured plan with action type, reconciled narrative, and reasoning.
   *
   * UPGRADE — Dimension 1 (Circuit Breaker): checks guard before LLM call.
   * UPGRADE — Dimension 2 (Arbitration Cache): deduplicates by conflict signature.
   */
  private async arbitrateConflict(
    threadA: NarrativeThread,
    threadB: NarrativeThread,
    conflict: SemanticConflict,
  ): Promise<ReconciliationPlan> {
    const chapterA = threadA.chapters[threadA.chapters.length - 1]
    const chapterB = threadB.chapters[threadB.chapters.length - 1]

    // ── Dimension 2: Check arbitration cache
    const arbKey = this.buildArbitrationKey(
      threadA.name,
      threadB.name,
      chapterA?.summary || "",
      chapterB?.summary || "",
      conflict.type,
    )
    const cachedPlan = this.arbitrationCache.get(arbKey)
    if (cachedPlan) {
      log.info("arbitration_cache_hit", {
        threadA: threadA.name,
        threadB: threadB.name,
        action: cachedPlan.action,
      })
      return cachedPlan
    }

    // ── Dimension 1: Check circuit breaker
    const guard = this.guardLLMCall()
    if (!guard.allowed) {
      log.debug("arbitration_llm_call_blocked_circuit_open")
      // Fallback to priority-based plan
      const fallbackPlan = this.buildFallbackPlan(threadA, threadB)
      return fallbackPlan
    }

    const prompt = `You are a master narrative editor resolving a conflict between two parallel story threads.

THREAD A: "${threadA.name}" (POV: ${threadA.povCharacter}, Priority: ${threadA.priority}/10)
Summary: ${chapterA?.summary || "N/A"}
Events: ${(chapterA?.events || []).join("; ") || "None"}
Characters present: ${(chapterA?.characters || []).join(", ")}
Location: ${chapterA?.location || "Unknown"}

THREAD B: "${threadB.name}" (POV: ${threadB.povCharacter}, Priority: ${threadB.priority}/10)
Summary: ${chapterB?.summary || "N/A"}
Events: ${(chapterB?.events || []).join("; ") || "None"}
Characters present: ${(chapterB?.characters || []).join(", ")}
Location: ${chapterB?.location || "Unknown"}

CONFLICT: ${conflict.description}
Type: ${conflict.type}
Thread A claims: ${conflict.conflictA}
Thread B claims: ${conflict.conflictB}

RESOLUTION OPTIONS:
1. modify_thread_a - Adjust Thread A's events to match Thread B's established reality
2. modify_thread_b - Adjust Thread B's events to match Thread A's established reality  
3. merge_events - Create a new narrative that combines both threads' truths
4. add_bridge - Add a transitional event that explains why the two threads differ (e.g., time dilation, unreliable narrator, dream sequence)

Choose the BEST option and explain. Output valid JSON:
{
  "action": "modify_thread_a" | "modify_thread_b" | "merge_events" | "add_bridge",
  "reconciledSummary": "The unified chapter summary both threads should converge toward",
  "reconciledEvents": ["event 1", "event 2", "event 3"],
  "reasoning": "Why this resolution makes the most narrative sense",
  "authoritativeThread": "name of the thread whose version is closer to the truth"
}`

    try {
      const response = await this.llmClient.call(prompt, {
        callType: "thread_arbitration",
      })

      // Parse the JSON response
      const jsonMatch = response.match(/\{[\s\S]*\}/)
      if (jsonMatch) {
        try {
          const plan = JSON.parse(jsonMatch[0]) as ReconciliationPlan
          // Validate required fields
          if (plan.action && plan.reconciledSummary && plan.reasoning) {
            const parsedPlan: ReconciliationPlan = {
              action: ["modify_thread_a", "modify_thread_b", "merge_events", "add_bridge"].includes(plan.action)
                ? plan.action
                : "merge_events",
              reconciledSummary: plan.reconciledSummary,
              reconciledEvents: Array.isArray(plan.reconciledEvents) ? plan.reconciledEvents : [],
              reasoning: plan.reasoning,
              authoritativeThread: plan.authoritativeThread || threadA.priority >= threadB.priority ? threadA.name : threadB.name,
            }
            // Cache the plan
            this.setArbitrationCache(arbKey, parsedPlan)
            this.recordLLMSuccess()
            return parsedPlan
          }
        } catch {
          // JSON parse failed, construct a reasonable plan manually
        }
      }

      // Fallback: construct a merge plan based on priorities
      this.recordLLMSuccess() // Call succeeded even if response was weird
      const fallbackPlan = this.buildFallbackPlan(threadA, threadB)
      this.setArbitrationCache(arbKey, fallbackPlan)
      return fallbackPlan
    } catch (e) {
      this.recordLLMFailure()
      log.warn("llm_arbitration_call_failed", {
        error: String(e),
        circuitState: this.circuitState,
        failureCount: this.llmFailureCount,
      })
      // Fall back to priority-based plan
      const fallbackPlan = this.buildFallbackPlan(threadA, threadB)
      this.setArbitrationCache(arbKey, fallbackPlan)
      return fallbackPlan
    }
  }

  /**
   * Build a priority-based reconciliation plan without LLM.
   * Used as fallback when circuit breaker is open or LLM call fails.
   */
  private buildFallbackPlan(
    threadA: NarrativeThread,
    threadB: NarrativeThread,
  ): ReconciliationPlan {
    const winner = threadA.priority >= threadB.priority ? threadA : threadB
    const loser = winner === threadA ? threadB : threadA
    const winnerChapter = winner.chapters[winner.chapters.length - 1]

    return {
      action: "merge_events",
      reconciledSummary: `${winner.name}'s version: ${winnerChapter?.summary || "N/A"}`,
      reconciledEvents: [
        ...(winnerChapter?.events || []),
        `Note: Reconciled with ${loser.name} (priority: ${winner.priority} vs ${loser.priority})`,
      ],
      reasoning: `LLM unavailable (circuit breaker or call failure). Using higher priority thread (${winner.name}, priority ${winner.priority}).`,
      authoritativeThread: winner.name,
    }
  }

  pauseThread(threadId: string): boolean {
    const thread = this.threads.get(threadId)
    if (!thread) return false

    thread.status = "paused"
    this.threads.set(threadId, thread)
    log.info("thread_paused", { threadId })

    return true
  }

  resumeThread(threadId: string): boolean {
    const thread = this.threads.get(threadId)
    if (!thread) return false

    thread.status = "active"
    this.threads.set(threadId, thread)
    log.info("thread_resumed", { threadId })

    return true
  }

  completeThread(threadId: string): boolean {
    const thread = this.threads.get(threadId)
    if (!thread) return false

    thread.status = "completed"
    this.threads.set(threadId, thread)
    log.info("thread_completed", { threadId })

    return true
  }

  mergeThreads(sourceThreadId: string, targetThreadId: string): boolean {
    const source = this.threads.get(sourceThreadId)
    const target = this.threads.get(targetThreadId)

    if (!source || !target) return false

    // Merge chapters
    target.chapters.push(...source.chapters)
    target.chapters.sort((a, b) => a.number - b.number)

    // Merge pending events
    target.pendingEvents.push(...source.pendingEvents)

    // Mark source as merged
    source.status = "merged"

    this.threads.set(sourceThreadId, source)
    this.threads.set(targetThreadId, target)
    log.info("threads_merged", { sourceThreadId, targetThreadId })

    return true
  }

  setConvergence(threadId1: string, threadId2: string): boolean {
    const thread1 = this.threads.get(threadId1)
    const thread2 = this.threads.get(threadId2)

    if (!thread1 || !thread2) return false

    if (!thread1.convergesWith) thread1.convergesWith = []
    if (!thread2.convergesWith) thread2.convergesWith = []

    if (!thread1.convergesWith.includes(threadId2)) {
      thread1.convergesWith.push(threadId2)
    }
    if (!thread2.convergesWith.includes(threadId1)) {
      thread2.convergesWith.push(threadId1)
    }

    this.threads.set(threadId1, thread1)
    this.threads.set(threadId2, thread2)
    log.info("convergence_set", { threadId1, threadId2 })

    return true
  }

  getThread(threadId: string): NarrativeThread | undefined {
    return this.threads.get(threadId)
  }

  getActiveThreads(): NarrativeThread[] {
    return Array.from(this.threads.values()).filter((t) => t.status === "active")
  }

  getThreadProgress(): Array<{
    threadId: string
    name: string
    chapter: number
    status: string
  }> {
    return Array.from(this.threads.values()).map((t) => ({
      threadId: t.id,
      name: t.name,
      chapter: t.currentChapter,
      status: t.status,
    }))
  }

  advanceGlobalChapter(): number {
    this.globalChapter++
    log.info("global_chapter_advanced", { chapter: this.globalChapter })
    return this.globalChapter
  }

  getGlobalChapter(): number {
    return this.globalChapter
  }

  getThreadReport(): string {
    const lines: string[] = ["# Multi-Thread Narrative Report\n"]

    const active = this.getActiveThreads()
    const paused = Array.from(this.threads.values()).filter((t) => t.status === "paused")
    const completed = Array.from(this.threads.values()).filter((t) => t.status === "completed")

    lines.push(`## Active Threads (${active.length})`)
    for (const thread of active.sort((a, b) => b.priority - a.priority)) {
      lines.push(`- **${thread.name}** (Priority: ${thread.priority})`)
      lines.push(`  - POV: ${thread.povCharacter}`)
      lines.push(`  - Chapter: ${thread.currentChapter}`)
      lines.push(`  - Pending Events: ${thread.pendingEvents.length}`)
      if (thread.convergesWith && thread.convergesWith.length > 0) {
        lines.push(`  - Converges with: ${thread.convergesWith.join(", ")}`)
      }
    }

    if (paused.length > 0) {
      lines.push(`\n## Paused Threads (${paused.length})`)
      for (const thread of paused) {
        lines.push(`- **${thread.name}** (Ch.${thread.currentChapter})`)
      }
    }

    if (completed.length > 0) {
      lines.push(`\n## Completed Threads (${completed.length})`)
      for (const thread of completed) {
        lines.push(`- **${thread.name}** (Completed at Ch.${thread.currentChapter})`)
      }
    }

    return lines.join("\n")
  }

  exportToJson(): { config: MultiThreadConfig; threads: NarrativeThread[]; globalChapter: number } {
    return {
      config: this.config,
      threads: Array.from(this.threads.values()),
      globalChapter: this.globalChapter,
    }
  }

  importFromJson(data: { config: MultiThreadConfig; threads: NarrativeThread[]; globalChapter: number }): void {
    this.config = { ...this.config, ...data.config }
    this.globalChapter = data.globalChapter
    for (const thread of data.threads) {
      this.threads.set(thread.id, thread)
    }
    log.info("multithread_narrative_imported", { threadCount: data.threads.length })
  }

  clear(): void {
    this.threads.clear()
    this.globalChapter = 1
    this.synchronizationBarriers.clear()
    log.info("multithread_narrative_cleared")
  }
}

export const multiThreadNarrativeExecutor = new MultiThreadNarrativeExecutor()
